### DISCUSSION TITLE
Pre-release 1.1.2

### DISCUSSION THREAD

**Discussion by YuuuXie** [mir-group/flare#313] [General]
## What's Changed

Full Changelog: https://github.com/mir-group/flare/compare/1.0.0...1.1.2

### Offline training
1. Compute and print mean absolute error at each step (frame), not only at steps where a frame is added to SGP. 
2. Add data distribution statistics at the end of the training, summarizing how many frames are picked up from each dataset

### Bug fixing
1. Fix a lammps calculator bug of prism cell
2. Fix the on-the-fly MAE calculation and logging when any of energy/forces/stress is excluded for training.
4. Allow DFT calculator to be saved as json in the checkpoint, in case some can be non-pickable
5. Add atom_indices into the dict of dumped SGP

### Other features and tutorials
1. Add timer for each part in OTF training log
2. Add mapped uncertainty to the `build_map` method in `SGP_Calculator`
3. Add python interface to support customized descriptors. Check the tutorial [here](https://colab.research.google.com/drive/1VzbIPmx1z-uygKstOYTj2Nqr53AMC5NL)
4. Add a tutorial for computing thermal conductivity from flare + [Phoebe](https://github.com/mir-group/phoebe). Check the tutorial [here](https://phoebe.readthedocs.io/en/develop/tutorials/mlPhononTransport.html)

### Backward compatibility notices
1. In the yaml file for offline training, the parameters in `FakeDFT` can be removed since they are redundant
  ```yaml
  dft_calc:
       name: FakeDFT
       kwargs: 
           filename: fake_dft.xyz
           format: extxyz
           index: ":"
           io_kwargs: {}
  ```
  change to 
  ```yaml
  dft_calc:
       name: FakeDFT
       kwargs: {} 
       params: {}
  ```

2. In the yaml file for offline training, the `filename` changes to `filenames`, allowing user to list multiple files as datasets.
  ```yaml
   otf: 
       md_engine: Fake
       md_kwargs: 
           filename: fake_dft.xyz
  ```
  change to
  ```yaml
   otf: 
       md_engine: Fake
       md_kwargs: 
           filenames: [fake_dft_1.xyz, fake_dft_2.xyz]
  ```
Then at the end of the training, the log file will report how many frames are selected to add to SGP from `fake_dft_1.xyz`, `fake_dft_2.xyz`, respectively.

3. In the yaml file for online or offline training, set up a lower bound of DFT calls for training hyperparameters
  ```yaml
  otf:
      freeze_hyps: 10
  ```
  change to 
  ```yaml
  otf:
      train_hyps: [1, 10]          # [a, b] represents training hyps when the number of DFT frames SGP has collected is between a and b
  ```

<hr /><em>This discussion was created from the release <a href='https://github.com/mir-group/flare/releases/tag/1.1.2'>Pre-release 1.1.2</a>.</em>
