### DISCUSSION TITLE
Energy hyperparameter has an offset?

### DISCUSSION THREAD

**Discussion by bastonero** [mir-group/flare#384] [Q&A]
Dear FLARE Developers,
I am using FLARE and it is amazing! Thanks a lot for this precious work! 
Currently I am trying to train  some snapshots of some materials ("offline" mode, using SGP Wrapper + B2 descriptors; see also attachment). Nevertheless, for different cases, MAE on forces and stresses are fine (~0.3 eV/Ang MAE for forces), whereas the energies have always a bigger error. 
Inspecting the output, I noticed that the hyperparameter of the energy is ~<Etot>, and if I subtract ( MAV-S_E ) / Nat ~ 0.1 eV, which would be a reasonable error. Here is the last part of the sdtout
```
Mean absolute errors & Mean absolute values
energy mae: 28662.2233 eV
energy mav: 28867.0624 eV
stress mae: 0.0021 eV/A^3
stress mav: 0.0051 eV/A^3
forces mae: 0.3296 eV/A
forces mav: 0.9431 eV/A
type 82 forces mae: 0.3919 eV/A
type 82 forces mav: 0.1833 eV/A
type 53 forces mae: 0.2898 eV/A
type 53 forces mav: 0.8769 eV/A
type 55 forces mae: 0.3865 eV/A
type 55 forces mav: 1.9017 eV/A

Uncertainty: [0.00388083 0.         0.        ]
Time of Update GP: 1.90 s
Time of Train Hyps: 98.09 s

GP hyperparameters:
Hyp0 : Hyp0                           = -2.1886
Hyp1 : Hyp1                           = 10.3087
Hyp2 : Hyp2                           = -28771.5235
Hyp3 : Hyp3                           = 0.5335
Hyp4 : Hyp4                           = 0.0021
Likelihood: -6066.0869
Likelihood gradient: [ 6.59480700e+01  4.52025492e+02  9.21402761e-06 -3.87215656e+02
  2.15562856e+03]
```

**Any suggestion how to fix this?**

Here is the input.yaml:
```yaml
# ===================== STRUCTURE ======================= #
supercell: 
  file: dataset.xyz
  format: extxyz
  index: 0
# ==================== DFT CALCULATOR ===================== #
dft_calc:
  name: FakeDFT
  kwargs: {} 
  params: {}
# ======================= GP/ML ========================= #
flare_calc:
  gp: SGP_Wrapper
  kernels:
    - name: NormalizedDotProduct
      sigma: 2.0
      power: 2
    - name: NormalizedDotProduct
      sigma: 2.0
      power: 0.5
  descriptors:
    - name: B2
      nmax: 16
      lmax: 8
      cutoff_function: quadratic
      radial_basis: chebyshev
      #cutoff_matrix: [[5.0, 4.0], [4.0, 5.0]]
    - name: B2
      nmax: 16
      lmax: 8
      cutoff_function: quadratic
      radial_basis: chebyshev
  energy_noise: 0.04
  forces_noise: 0.05
  stress_noise: 0.005
  species:
    - 53 # I                                            
    - 55 # Cs
    - 82 # Pb 
  single_atom_energies: # ['Cs', -632.027637488, 'I', -2702.7083376388rm, 'Pb', -11689.338427714]
  #  - 2702.7083376388
  #  - 632.027637488
  #  - 11689.338427714
   - 0
   - 0
   - 0
  cutoff: 5.0
  variance_type: local
  max_iterations: 1000
  use_mapping: False
  energy_training: true
  force_training: true
  stress_training: true
# ======================= OTF & MD ========================= #
otf: 
  mode: fresh
  md_engine: Fake
  md_kwargs: 
      filenames:
        - dataset.xyz
      format: extxyz
      index: ":"
      io_kwargs: {}                            
  dt: 0.001                         
  number_of_steps: 84 # <= num. frames          
  output_name: offline            
  init_atoms: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]        
  std_tolerance_factor: -0.01
  max_atoms_added: -1
  train_hyps: [0, 84]
  write_model: 1
  update_style: threshold
  build_mode: bayesian
  update_threshold: 0.001
  force_only: False

```
