### ISSUE TITLE
Wrong `QE` DFT calculator name in GoogleColab tutorial?

### ISSUE THREAD

**Issue by bastonero** [mir-group/flare#369]
**Describe the bug**
The name of the Quantum ESPRESSO calculator is wrong in the GColab tutorial. It is currently reported `QE`. This prints out the error message

> ModuleNotFoundError: No module named 'ase.calculators.'

which is rather misleading. One might think to have some environment issues (I had to look into the flare source code and debug the method to understand it wasn't an installation issue).

**To Reproduce**
1. Use
 ```yaml
dft_calculator:
    name: QE
```
 in the yaml file for `flare-otf`.

**Expected behavior**
I think the following improvements might be considered:
1. Document better what is meant by `name` in `dft_calculator`
2. Better error message. Considering to except the `ModuleNotFoundError` with some other error, possibly indicating that the wrong name is being used.

When using `Espresso` instead of `QE` everything is working properly.

**Comment by bastonero** [comment]
I think also these other thins are incorrect:
```yaml
dft_calc:
    command: "mpirun ..."
    kwargs:
        kpts: (8,8,8)
        ...
```
should be under `kwargs`, and `kpts` should be specified with the square brackets `[8,8,8]`, NOT `(8,8,8)`.
Hence, the correct version:
```yaml
dft_calc:
    kwargs:
        command: "mpirun ..."
        kpts: [8,8,8]
        ...
```
